dataset_params: 
  training_type: "imitation_learning" # "ppo_amp", "ppo", "imitation_learning"
  dataset_path: "/home/valerio/g1_hybrid_prior/data_raw/LAFAN1_Retargeting_Dataset/g1_body_fk_npz_partial"
  robot: "g1" # "g1" or "g1_amp"
  dataset_type: "augmented" # "raw" or "augmented"
  lazy_load: False
  vel_mode: "central" # "central" or "backward"
  num_amp_obs_steps : 2
  max_rot_reset: False
  early_termination_dist_threshold: 0.5
  early_term_rot_threshold_deg: 90.0
  upper_names:
    - "left_shoulder_pitch_link"
    - "left_shoulder_roll_link"
    - "left_shoulder_yaw_link"
    - "left_elbow_link"
    - "left_wrist_roll_link"
    - "left_wrist_pitch_link"
    - "left_wrist_yaw_link"
    - "right_shoulder_pitch_link"
    - "right_shoulder_roll_link"
    - "right_shoulder_yaw_link"
    - "right_elbow_link"
    - "right_wrist_roll_link"
    - "right_wrist_pitch_link"
    - "right_wrist_yaw_link"
  vx_range: [-0.5, 3.0]
  vy_range: [-0.8, 0.8]
  orientation_range: [-180.0, 180.0]
  max_omega: 0.2
  cmd_resample_seconds: 2.5
  rew_w_in_vel: 1.0
  rew_w_ang_vel: 0.5
  rew_w_lin_vel_penalty: 5.0
  rew_w_ang_vel_penalty: 2.0 
  vx_shrink_factor: 1.5
  omega_decay_threshold: 3.0



#/home/valerio/g1_hybrid_prior/data_raw/LAFAN1_Retargeting_Dataset/g1_ee_augmented/walk1_subject1.csv
#/home/valerio/g1_hybrid_prior/data_raw/LAFAN1_Retargeting_Dataset/g1_ee_augmented_partial_data
#/home/valerio/g1_hybrid_prior/data_raw/LAFAN1_Retargeting_Dataset/g1_body_fk_npz_partial

